source ~/colemak.vim
set encoding=utf-8
"set fillchars+=stl:\ ,stlnc:\
"let g:Powerline_symbols = 'fancy'
set runtimepath^=~/.vim/bundle/ctrlp.vim
set runtimepath^=~/.vim/bundle/vim-airline
let g:airline_powerline_fonts=1
let g:airline_theme="solarized"
"set runtimepath^=~/.vim/bundle/vim-powerline
"set nocompatible
set laststatus=2
"colorscheme monokai
