#! /bin/sh

### Theme ###
export THEME='virtualself'

### Auxiliary Programs ###
if ! pgrep -x "sxhkd" > /dev/null; then sxhkd -m -1; fi &
if ! pgrep -x "polybar" > /dev/null; then $HOME/.config/polybar/launch.sh $THEME; fi &
xsetroot -cursor_name left_ptr &

### Workspaces ###
bspc monitor -d I II III IV V VI VII VIII IX X

#bspc config focus_follows_pointer true

### Pointer Settings ###
bspc config focus_follows_pointer "${setting_focus_follows_pointer:-true}"
bspc config ignore_ewmh_focus "${setting_ignore_ewmh_focus:-true}"
bspc config pointer_modifier mod1 

### Options ###
bspc config automatic_scheme longest_side
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

### Apply Theme ###
$HOME/.config/bspwm/themes/$THEME.sh

### External Rules ###
bspc config external_rules_command ~/.config/bspwm/rules/external_rules.sh
