vim.o.number = true -- show line numbers
vim.o.ignorecase = true -- search case
vim.o.smartcase = true -- search case
vim.o.expandtab = true -- spaces instead of tabs
vim.o.tabstop = 4 -- tab length
vim.o.shiftwidth = 4 -- tab length
vim.o.clipboard = "unnamedplus" -- share system clipboard
vim.o.whichwrap = "b,s,[,],<,>,h,l" -- allow cursor to wrap between lines
vim.o.virtualedit = "block"	-- allow virtual editing in Visual block mode
vim.o.lazyredraw = true		-- don't redraw screen while executing macros/mappings
vim.o.scrolloff = 1		-- minimal number of screen lines to keep above and below the cursor
